# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\rmessage_queue\"\x1d\n\x07Message\x12\x12\n\nqueue_name\x18\x01 \x01(\t\"}\n\x12GetMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x04 \x01(\t\x12\x0f\n\x07service\x18\x05 \x01(\t\x12\x12\n\nqueue_name\x18\x06 \x01(\t\"n\n\x12SendMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x10\n\x08response\x18\x04 \x01(\t\x12\x12\n\nqueue_name\x18\x05 \x01(\t\"6\n\x13SendMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xad\x01\n\x0cMessageQueue\x12G\n\ngetMessage\x12\x16.message_queue.Message\x1a!.message_queue.GetMessageResponse\x12T\n\x0bsendMessage\x12!.message_queue.SendMessageRequest\x1a\".message_queue.SendMessageResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=29
  _MESSAGE._serialized_end=58
  _GETMESSAGERESPONSE._serialized_start=60
  _GETMESSAGERESPONSE._serialized_end=185
  _SENDMESSAGEREQUEST._serialized_start=187
  _SENDMESSAGEREQUEST._serialized_end=297
  _SENDMESSAGERESPONSE._serialized_start=299
  _SENDMESSAGERESPONSE._serialized_end=353
  _MESSAGEQUEUE._serialized_start=356
  _MESSAGEQUEUE._serialized_end=529
# @@protoc_insertion_point(module_scope)
